const constants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_LOADING: "LOGIN_LOADING",

  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  REGISTRATION_LOADING: "REGISTRATION_LOADING",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_LOADING: "LOGOUT_LOADING",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_ROLE_LOADING: "GET_ROLE_LOADING",
  GET_ROLE_FAILED: "GET_ROLE_FAILED",

  ADD_AUTHORS_SUCCESS: "ADD_AUTHORS_SUCCESS",
  ADD_AUTHORS_LOADING: "ADD_AUTHORS_LOADING",
  ADD_AUTHORS_FAILED: "ADD_AUTHORS_FAILED",

  GET_AUTHORS_SUCCESS: "GET_AUTHORS_SUCCESS",
  GET_AUTHORS_LOADING: "GET_AUTHORS_LOADING",
  GET_AUTHORS_FAILED: "GET_AUTHORS_FAILED",

  GET_GENRES_SUCCESS: "GET_GENRES_SUCCESS",
  GET_GENRES_LOADING: "GET_GENRES_LOADING",
  GET_GENRES_FAILED: "GET_GENRES_FAILED",

  ADD_GENRE_SUCCESS: "ADD_GENRE_SUCCESS",
  ADD_GENRE_LOADING: "ADD_GENRE_LOADING",
  ADD_GENRE_FAILED: "ADD_GENRE_FAILED",

  DELETE_GENRE_SUCCESS: "DELETE_GENRE_SUCCESS",
  DELETE_GENRE_LOADING: "DELETE_GENRE_LOADING",
  DELETE_GENRE_FAILED: "DELETE_GENRE_FAILED",

  GET_ALL_SONGS_SUCCESS: "GET_ALL_SONGS_SUCCESS",
  GET_ALL_SONGS_LOADING: "GET_ALL_SONGS_LOADING",
  GET_ALL_SONGS_FAILED: "GET_ALL_SONGS_FAILED",

  GET_FILTERED_SONGS_SUCCESS: "GET_FILTERED_SONGS_SUCCESS",
  GET_FILTERED_SONGS_LOADING: "GET_FILTERED_SONGS_LOADING",
  GET_FILTERED_SONGS_FAILED: "GET_FILTERED_SONGS_FAILED",

  ADD_SONG_SUCCESS: "ADD_SONG_SUCCESS",
  ADD_SONG_LOADING: "ADD_SONG_LOADING",
  ADD_SONG_FAILED: "ADD_SONG_FAILED",

  ADD_ALBUM_SUCCESS: "ADD_ALBUM_SUCCESS",
  ADD_ALBUM_LOADING: "ADD_ALBUM_LOADING",
  ADD_ALBUM_FAILED: "ADD_ALBUM_FAILED",

  GET_ALL_ALBUMS_SUCCESS: "GET_ALL_ALBUMS_SUCCESS",
  GET_ALL_ALBUMS_LOADING: "GET_ALL_ALBUMS_LOADING",
  GET_ALL_ALBUMS_FAILED: "GET_ALL_ALBUMS_FAILED",

  GET_ONE_ALBUM_SUCCESS: "GET_ONE_ALBUM_SUCCESS",
  GET_ONE_ALBUM_LOADING: "GET_ONE_ALBUM_LOADING",
  GET_ONE_ALBUM_FAILED: "GET_ONE_ALBUM_FAILED",

  ADD_SONG_TO_ALBUM_SUCCESS: "ADD_SONG_TO_ALBUM_SUCCESS",
  ADD_SONG_TO_ALBUM_LOADING: "ADD_SONG_TO_ALBUM_LOADING",
  ADD_SONG_TO_ALBUM_FAILED: "ADD_SONG_TO_ALBUM_FAILED",

  DELETE_SONG_FROM_ALBUM_SUCCESS: "DELETE_SONG_FROM_ALBUM_SUCCESS",
  DELETE_SONG_FROM_ALBUM_LOADING: "DELETE_SONG_FROM_ALBUM_LOADING",
  DELETE_SONG_FROM_ALBUM_FAILED: "DELETE_SONG_FROM_ALBUM_FAILED",

  LK_ADD_SONG_TO_LIST_SUCCESS: "LK_ADD_SONG_TO_LIST_SUCCESS",
  LK_ADD_SONG_TO_LIST_LOADING: "LK_ADD_SONG_TO_LIST_LOADING",
  LK_ADD_SONG_TO_LIST_FAILED: "LK_ADD_SONG_TO_LIST_FAILED",

  LK_GET_SONG_FROM_LIST_SUCCESS: "LK_GET_SONG_FROM_LIST_SUCCESS",
  LK_GET_SONG_FROM_LIST_LOADING: "LK_GET_SONG_FROM_LIST_LOADING",
  LK_GET_SONG_FROM_LIST_FAILED: "LK_GET_SONG_FROM_LIST_FAILED",

  LK_DELETE_SONG_FROM_LIST_SUCCESS: "LK_DELETE_SONG_FROM_LIST_SUCCESS",
  LK_DELETE_SONG_FROM_LIST_LOADING: "LK_DELETE_SONG_FROM_LIST_LOADING",
  LK_DELETE_SONG_FROM_LIST_FAILED: "LK_DELETE_SONG_FROM_LIST_FAILED",

  LK_GET_PLAYLISTS_SUCCESS: "LK_GET_PLAYLISTS_SUCCESS",
  LK_GET_PLAYLISTS_LOADING: "LK_GET_PLAYLISTS_LOADING",
  LK_GET_PLAYLISTS_FAILED: "LK_GET_PLAYLISTS_FAILED",

  LK_GET_PLAYLIST_SUCCESS: "LK_GET_PLAYLIST_SUCCESS",
  LK_GET_PLAYLIST_LOADING: "LK_GET_PLAYLIST_LOADING",
  LK_GET_PLAYLIST_FAILED: "LK_GET_PLAYLIST_FAILED",

  LK_DELETE_PLAYLIST_SUCCESS: "LK_DELETE_PLAYLIST_SUCCESS",
  LK_DELETE_PLAYLIST_LOADING: "LK_DELETE_PLAYLIST_LOADING",
  LK_DELETE_PLAYLIST_FAILED: "LK_DELETE_PLAYLIST_FAILED",

  LK_ADD_PLAYLIST_SUCCESS: "LK_ADD_PLAYLIST_SUCCESS",
  LK_ADD_PLAYLIST_LOADING: "LK_ADD_PLAYLIST_LOADING",
  LK_ADD_PLAYLIST_FAILED: "LK_ADD_PLAYLIST_FAILED",

  LK_ADD_SONG_TO_PLAYLIST_SUCCESS: "LK_ADD_SONG_TO_PLAYLIST_SUCCESS",
  LK_ADD_SONG_TO_PLAYLIST_LOADING: "LK_ADD_SONG_TO_PLAYLIST_LOADING",
  LK_ADD_SONG_TO_PLAYLIST_FAILED: "LK_ADD_SONG_TO_PLAYLIST_FAILED",

  LK_DELETE_SONG_FROM_PLAYLIST_SUCCESS: "LK_DELETE_SONG_FROM_PLAYLIST_SUCCESS",
  LK_DELETE_SONG_FROM_PLAYLIST_LOADING: "LK_DELETE_SONG_FROM_PLAYLIST_LOADING",
  LK_DELETE_SONG_FROM_PLAYLIST_FAILED: "LK_DELETE_SONG_FROM_PLAYLIST_FAILED",

  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_LOADING: "GET_ALL_USERS_LOADING",
  GET_ALL_USERS_FAILED: "GET_ALL_USERS_FAILED",

  GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_LOADING: "GET_USER_LIST_LOADING",
  GET_USER_LIST_FAILED: "GET_USER_LIST_FAILED",
}
export default constants
